### ISSUE TITLE
Missing svg files in zip file, which is still been used in theme

### ISSUE THREAD

**Issue by chihchun** [alpha-rudy/taiwan-topo#31] opened 2018-08-20 08:22 UTC
```
% date -r MOI_OSM_Taiwan_TOPO_Rudy_style.zip -R
Thu, 16 Aug 2018 04:56:47 +0800
% sha256sum MOI_OSM_Taiwan_TOPO_Rudy_style.zip
a9784ccf4e31624e1da5c784737b031175d5ff9eacd25ee6dab601c1bd042e02 MOI_OSM_Taiwan_TOPO_Rudy_style.zip
```

Errors

```
SEVERE: invalid resource: moiosm_res/s_pt_bus_station.svg
SEVERE: invalid resource: moiosm_res/s_pt_bus.svg
SEVERE: invalid resource: moiosm_res/s_pt_rail_lz.svg
SEVERE: invalid resource: moiosm_res/s_pt_rail.svg
SEVERE: invalid resource: moiosm_res/s_pt_subway.svg
```

usage in theme
```
% grep s_pt_bus_station.svg styles/*/*xml
styles/locus_lite/MOI_OSM_Lite.xml: <symbol id="s_pt_bus_station" priority="112" src="file:moiosmlite_res/s_pt_bus_station.svg" symbol-scaling="size" symbol-height="12" symbol-width="12"/>
styles/locus_style/MOI_OSM.xml: <symbol id="s_pt_bus_station" priority="112" src="file:moiosm_res/s_pt_bus_station.svg" symbol-scaling="size" symbol-height="12" symbol-width="12"/>
styles/mapsforge_hs/MOI_OSM.xml: <symbol id="s_pt_bus_station" priority="112" src="file:moiosmhs_res/s_pt_bus_station.svg" symbol-scaling="size" symbol-height="12" symbol-width="12"/>
styles/mapsforge_lite/MOI_OSM_Lite.xml: <symbol id="s_pt_bus_station" priority="112" src="file:moiosmlite_res/s_pt_bus_station.svg" symbol-scaling="size" symbol-height="12" symbol-width="12"/>
styles/mapsforge_style/MOI_OSM.xml: <symbol id="s_pt_bus_station" priority="112" src="file:moiosm_res/s_pt_bus_station.svg" symbol-scaling="size" symbol-height="12" symbol-width="12"/>
styles/twmap_style/MOI_OSM_twmap.xml: <symbol id="s_pt_bus_station" priority="112" src="file:moiosm_twmap/s_pt_bus_station.svg" symbol-scaling="size" symbol-height="12" symbol-width="12"/>
```

**Comment by typebrook** [comment] 2018-08-20 11:09
Caused by some rules use deleted/renamed svg file. 
[s_pt_bus_station.svg -> bus_station_a.svg](https://github.com/alpha-rudy/taiwan-topo/commit/7bb42994d937552ed343f455dc836bbade01e381?short_path=96e44d8#diff-ade1d5685c10e456983d4aea38eb9c07)
[s_pt_rail.svg -> s_pt_rail_taiwan.svg](https://github.com/alpha-rudy/taiwan-topo/commit/29137a3e75347bce94bc177255fb4b3983f432f9#diff-7af9759838302adeef9f39dc2b50b1fc)
[s_pt_bus.svg -> s_pt_bus_stop.svg/s_pt_bus_stop_shelter.svg](https://github.com/alpha-rudy/taiwan-topo/commit/40c9dab6eb028ed40a5e6c05c9a44e3e81c20a2a#diff-153edc5095d3ebfc4476172c45e11cf7)
[s_pt_subway.svg -> s_pt_subway_taipei.svg](https://github.com/alpha-rudy/taiwan-topo/commit/29137a3e75347bce94bc177255fb4b3983f432f9#diff-c485d474ebe24b3c2e216d3743427a5e)

8381cb6aecdad25167530363a92aed630a0a830c apply newer svg files for these rules, should fix the problem. @alpha-rudy please check this modify goes well

**Comment by typebrook** [comment] 2018-08-20 11:18
[s_pt_rail_lz.svg -> s_pt_rail_taiwan.svg](https://github.com/alpha-rudy/taiwan-topo/commit/29137a3e75347bce94bc177255fb4b3983f432f9#diff-a2c96c5fc515b9a082bb9ed8b6ec2ed7)
forgot to deal with s_pt_rail_lz.svg 5cf2306de903d891472525dc00ba529f1a9487d5

**Comment by alpha-rudy** [comment] 2018-08-20 14:25
Hi @chihchun , 

The only visible layer is "elmt-hiking". 

"elmt-city", "elmt-cycling", and "elmt-mtb" are all not visible. Are all these errors come from "elmt-hiking"?

Sincerely,
Rudy  8/20

**Comment by chihchun** [comment] 2018-08-29 15:41
On the server side mapsforge render, it will valid all style and image files are exist.

**Comment by typebrook** [comment] 2018-08-30 10:14
Since missing files are fixed with newer svg file name, this issue should be closed.
https://github.com/alpha-rudy/taiwan-topo/commit/8381cb6aecdad25167530363a92aed630a0a830c#r30208126

**Closed as completed** 2018-08-30 10:14 UTC
